spring.application.name=smartcampus
server.port=8081

spring.datasource.url=jdbc:postgresql://ep-jolly-firefly-am4bnxj0.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&sslNegotiation=direct&channelBinding=require&options=endpoint%3Dep-jolly-firefly-am4bnxj0&connectTimeout=30&socketTimeout=60&loginTimeout=30
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2MRb9wdAUlJi
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

spring.security.oauth2.client.registration.google.client-id=292463357916-8mm99cutofjhf154iiqoocku8m1uedv6.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile